# Generated by Django 4.0.4 on 2022-08-23 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
