# Generated by Django 4.0.4 on 2022-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
