# Generated by Django 4.0.4 on 2022-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currentPrice',
            field=models.PositiveIntegerField(help_text='Not to exceed 2147483647!'),
        ),
    ]
