# Generated by Django 4.0.4 on 2022-08-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_currentprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='currentPrice',
            new_name='price',
        ),
    ]
